
server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER


  cloud:
    config:
      server:
        git:
          uri: https://github.com/manishaverma1012/microservices-configserver
          clone-on-start: true