spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Microservices


  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8085
server:
  port: 8081




#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8671/eureka
